services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: myuser
      DATABASE_PASSWORD: mypassword
      DATABASE_NAME: mydatabase
      REDIS_HOST: redis
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis
    ports:
      - "3001:3000"

volumes:
  postgres_data:
  redis_data:
